services:
  server:
    build: .
    restart: unless-stopped
    volumes:
      - ./config:/etc/ckpool
      - ./logs:/var/log/ckpool
      - ./data:/var/lib/ckpool
    ports:
      - "3333:3333"
      - "3334:3334"
    environment:
      - CKPOOL_CONFIG=/etc/ckpool/ckpool.conf
      - POSTGRES_PASSWORD=changeme123
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ckpool
      POSTGRES_USER: ckpool
      POSTGRES_PASSWORD: changeme123
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ckpool -d ckpool"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s